name: Manually Publish

on:
  workflow_dispatch:
    inputs:
      chosen-os:
        description: "os to publish"
        required: true
        type: choice
        options:
        - ubuntu-latest
        - windows-latest
        - macos-latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Wheels on ${{ inputs.chosen-os }}
    runs-on: ${{ inputs.chosen-os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - uses: lukka/get-cmake@latest
      if: matrix.os != 'ubuntu-latest'
    - name: Setup anew (or from cache) vcpkg (and does not build any package)
      if: matrix.os != 'ubuntu-latest'
      uses: lukka/run-vcpkg@v11 # Always specify the specific _version_ of the
                                # action you need, `v11` in this case to stay up
                                # to date with fixes on the v11 branch.

    - uses: pypa/cibuildwheel@v2.17
      env:
        CIBW_SKIP: pp* *_i686
        MACOSX_DEPLOYMENT_TARGET: 10.14

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl


  upload_all:
    name: Upload
    needs: [build_wheels]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.8.14
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
